version: '2'
services:
  mopin-admin:
    image: mopin/admin
    ports:
      - "8080:8080"
    environment:
      - spring.profiles.active=dev
  mopin-api:
    image: mopin/api
    ports:
      - "8081:8081"
    environment:
      - spring.profiles.active=dev
